function mDisplayEPRfiles_aboutProgram_v_01 (B) 
% Вызов дополнительного окна с информацией о программе
B = getappdata(B.hFig,'B');
% figure(B.hFig);
hFpos = get(B.hFig,'Position');
pl = hFpos(1);
pu = hFpos(2);
wscr = hFpos(3);
hscr = hFpos(4);
B.hFigAbout_Width = 1.75*B.lb_width;
% B.hFigOptions_High = 2*B.lb_High;
B.hFigAbout_High = 700;
dpu = round((hscr - (20+20)-B.hFigAbout_High)/2);
checkBopt = isfield(B,'hFigAbout');
if ~checkBopt
    B.hFigAbout = figure('Position', [pl+40,...
                                    pu+dpu ...
                                    B.hFigAbout_Width ...
                                    B.hFigAbout_High], 'MenuBar', 'none', 'NumberTitle','off','Name','About program GNU D''EPRnian', 'Resize', 'off', 'Color', B.figColorBG+0.1);
    LimitSizeFig(B.hFigAbout, 'min', [B.hFigAbout_Width, B.hFigAbout_High]);
    
else
    if ~ishandle(B.hFigAbout) 
        B.hFigAbout = figure('Position', [pl+40,...
                                            pu+dpu ...
                                            B.hFigAbout_Width ...
                                            B.hFigAbout_High], 'MenuBar', 'none', 'Name','About program GNU D''EPRnian', 'NumberTitle','off', 'Resize', 'off', 'Color', B.figColorBG+0.1);
        LimitSizeFig(B.hFigAbout, 'min', [B.hFigAbout_Width, B.hFigAbout_High]);                                 
    else
        figure(B.hFigAbout);
        set(B.hFigAbout, 'HandleVisibility', 'on');
%         hFpos = get(B.hFigOptions,'Position');
        uistack(B.hFigAbout, 'top' );
%         jFrame = get(gcf,'JavaFrame');
%         jFrame.setMaximized(true);
%         set(B.hFigOptions,'Position',hFpos);
    end

end

            warning('off','MATLAB:HandleGraphics:ObsoletedProperty:JavaFrame');
            jframe=get(B.hFigAbout,'javaframe');
            jIcon=javax.swing.ImageIcon('./icons/main/default_icon.png');
            jframe.setFigureIcon(jIcon);

% 
%     setappdata(B.hFig,'B',B);
%     mDisplayEPRfiles_pltData_v_02(B);
%     B = getappdata(B.hFig,'B'); 
txt = ['     Program %s \n',...
    '________________________________________________\n',...
    '                      Authors:\n',...
    '     Yevgen Syryanyy (Zhenia Syriany)\n',...
    ' email: yuginboy@gmail.com\n',...
    ' Institute of Physics, Polish Academy of Sciences\n',...
    ' al. Lotnikow 32/46\nPL 02-668 Warsaw, Poland \n',...
    '                        and\n',...
    '     Andrey Prokhorov\n',...
    ' email: andaprokhorov@gmail.com\n',...
    ' A.A. Galkin Donetsk Physico-Technical Institute\n',...
    ' 83114 Donetsk, R. Luxembourg str. 72\n',...
    '________________________________________________\n',...
    'This program has been created for all people who wants to have a GUI comfort to analize the EPR spectra.\n',...
    'GNU General Public License for this program excluding following packages:\n',...
    'EasySpin. EasySpin is a MATLAB toolbox for simulating and fitting Electron Paramagnetic Resonance (EPR) spectra. (http://www.easyspin.org/)\n',...
    ' LimitSizeFig. Author: Jan Simon'];
txt = sprintf(txt, B.verVar);
% txt_about = uibutton('Style','text','Value',1,...
%                'Units','Pixels',...
%                'Position',[10 10 B.hFigAbout_Width-20, B.hFigAbout_High-20],...
%                'String',txt, 'Interpreter', 'latex');
txt_about = uicontrol('Style','text','Value',1,...
               'Units','Pixels','Selected', 'on', 'SelectionHighlight', 'on',...
               'Position',[10 10, B.hFigAbout_Width-20, B.hFigAbout_High-20],...
               'String',txt, 'FontSize', 10); 
% mytext = ['<html><body><table border="1">' ...
%           '<tr><th>Month</th><th>Savings</th></tr>' ...
%           '<tr><td>January</td><td>$100</td></tr>' ...
%           '</table></body></html>'];
 
% % Create a figure with a scrollable JEditorPane
% % hfig = figure();
% je = javax.swing.JEditorPane('text/html', mytext);
% jp = javax.swing.JScrollPane(je);
% [hcomponent, hcontainer] = javacomponent(jp, [], B.hFigAbout);
% set(hcontainer, 'units', 'normalized', 'position', [0,0,1,1]);
%  
% % Turn anti-aliasing on (R2006a, Java 5.0)
% java.lang.System.setProperty('awt.useSystemAAFontSettings', 'on');
% je.setFont(java.awt.Font('Arial', java.awt.Font.PLAIN, 13));
% je.putClientProperty(javax.swing.JEditorPane.HONOR_DISPLAY_PROPERTIES, true);
%  
% % This only works on Java 1.5 (Matlab R14SP2 to R2007a):
% je.putClientProperty(com.sun.java.swing.SwingUtilities2.AA_TEXT_PROPERTY_KEY, true);


setappdata(B.hFig,'B',B);

end